//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/MainController.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MainController: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MainController()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MainController"",
    ""maps"": [
        {
            ""name"": ""MainMap"",
            ""id"": ""39128c6f-76a6-4f6d-9271-87caa951a749"",
            ""actions"": [
                {
                    ""name"": ""Launch"",
                    ""type"": ""Button"",
                    ""id"": ""113f192c-cacf-41ce-983c-9a2f657f596e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Flipper_L"",
                    ""type"": ""Button"",
                    ""id"": ""9d507520-7f09-488b-b291-490479752254"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Flipper_R"",
                    ""type"": ""Button"",
                    ""id"": ""42971da1-b9db-494d-b97d-ad1c41a1de54"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reload"",
                    ""type"": ""Button"",
                    ""id"": ""405b01f3-af11-4b17-b183-9fa45aab791e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""fdf57218-34ed-4c0f-b0e2-a435c8654bf7"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Launch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f6145fc6-d981-4001-adb2-195e17ecd26b"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Flipper_L"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""03f697c1-4d74-4313-a6f2-efcd32f8c082"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Flipper_R"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cb146545-96b4-4629-8362-eb4056880e08"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reload"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // MainMap
        m_MainMap = asset.FindActionMap("MainMap", throwIfNotFound: true);
        m_MainMap_Launch = m_MainMap.FindAction("Launch", throwIfNotFound: true);
        m_MainMap_Flipper_L = m_MainMap.FindAction("Flipper_L", throwIfNotFound: true);
        m_MainMap_Flipper_R = m_MainMap.FindAction("Flipper_R", throwIfNotFound: true);
        m_MainMap_Reload = m_MainMap.FindAction("Reload", throwIfNotFound: true);
    }

    ~@MainController()
    {
        UnityEngine.Debug.Assert(!m_MainMap.enabled, "This will cause a leak and performance issues, MainController.MainMap.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // MainMap
    private readonly InputActionMap m_MainMap;
    private List<IMainMapActions> m_MainMapActionsCallbackInterfaces = new List<IMainMapActions>();
    private readonly InputAction m_MainMap_Launch;
    private readonly InputAction m_MainMap_Flipper_L;
    private readonly InputAction m_MainMap_Flipper_R;
    private readonly InputAction m_MainMap_Reload;
    public struct MainMapActions
    {
        private @MainController m_Wrapper;
        public MainMapActions(@MainController wrapper) { m_Wrapper = wrapper; }
        public InputAction @Launch => m_Wrapper.m_MainMap_Launch;
        public InputAction @Flipper_L => m_Wrapper.m_MainMap_Flipper_L;
        public InputAction @Flipper_R => m_Wrapper.m_MainMap_Flipper_R;
        public InputAction @Reload => m_Wrapper.m_MainMap_Reload;
        public InputActionMap Get() { return m_Wrapper.m_MainMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MainMapActions set) { return set.Get(); }
        public void AddCallbacks(IMainMapActions instance)
        {
            if (instance == null || m_Wrapper.m_MainMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MainMapActionsCallbackInterfaces.Add(instance);
            @Launch.started += instance.OnLaunch;
            @Launch.performed += instance.OnLaunch;
            @Launch.canceled += instance.OnLaunch;
            @Flipper_L.started += instance.OnFlipper_L;
            @Flipper_L.performed += instance.OnFlipper_L;
            @Flipper_L.canceled += instance.OnFlipper_L;
            @Flipper_R.started += instance.OnFlipper_R;
            @Flipper_R.performed += instance.OnFlipper_R;
            @Flipper_R.canceled += instance.OnFlipper_R;
            @Reload.started += instance.OnReload;
            @Reload.performed += instance.OnReload;
            @Reload.canceled += instance.OnReload;
        }

        private void UnregisterCallbacks(IMainMapActions instance)
        {
            @Launch.started -= instance.OnLaunch;
            @Launch.performed -= instance.OnLaunch;
            @Launch.canceled -= instance.OnLaunch;
            @Flipper_L.started -= instance.OnFlipper_L;
            @Flipper_L.performed -= instance.OnFlipper_L;
            @Flipper_L.canceled -= instance.OnFlipper_L;
            @Flipper_R.started -= instance.OnFlipper_R;
            @Flipper_R.performed -= instance.OnFlipper_R;
            @Flipper_R.canceled -= instance.OnFlipper_R;
            @Reload.started -= instance.OnReload;
            @Reload.performed -= instance.OnReload;
            @Reload.canceled -= instance.OnReload;
        }

        public void RemoveCallbacks(IMainMapActions instance)
        {
            if (m_Wrapper.m_MainMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMainMapActions instance)
        {
            foreach (var item in m_Wrapper.m_MainMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MainMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MainMapActions @MainMap => new MainMapActions(this);
    public interface IMainMapActions
    {
        void OnLaunch(InputAction.CallbackContext context);
        void OnFlipper_L(InputAction.CallbackContext context);
        void OnFlipper_R(InputAction.CallbackContext context);
        void OnReload(InputAction.CallbackContext context);
    }
}
